baseURL = "https://rh-aquatic.com"
#baseURL = "http://localhost:1313"
title = "潤宏水産"
theme = "ananke"

DefaultContentLanguage = "ja"
DefaultContentLanguageInSubdir = true

[languages]
  [languages."ja"]
    languageName = "Japanese"
    weight = 20
    title = "潤宏水産・Home"
  [languages."zh"]
    languageName = "Chinese"
    weight = 20
    title = "润宏水产/Home"
